version: '3.8'

services:
  markdown-notebook:
    build: .
    ports:
      - "5001:5001"
      - "3000:3000"
    volumes:
      - ./notes:/app/notes
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped 