version: '3.8'

services:
  markdown-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdown-notebook
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./notes:/app/notes
    environment:
      - PORT=5000
      - NOTES_DIR=/app/notes 